version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: "echo hello "
  
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say World"
          command: "echo world"

  print_name:
    docker:
      - image: cimg/base:2021.11
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_NAME

workflows:
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_name

