version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say Hello"
          command: echo "hello Ramin" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2021.11
    steps:
      - checkout
      - run:
          name: "print output file"
          command: |
            cat ~/output.txt
      - attach_workspace:
          at: ~/

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file

