version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say Hello"
          command: echo "hello Ramin" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
            at: ~/
      - run:
          name: "print output file"
          command: |
            cat ~/output.txt

  my_job_for_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  
  my_job_when_fails_example:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail

workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - my_job_for_command
      - my_job_when_fails_example

